// vue/shoppinglist/src/components/ShoppingList.vue
<template>
	<table>
		<thead>
			<tr>
				<th>Count</th>
				<th>Type</th>
				<th>Price</th>
				<th>Buy</th>
			</tr>
		</thead>
		<tbody>
			<tr v-for="(item,index) in list" :key="item.id">
				<td>{{item.count}}</td>
				<td>{{item.itemtype}}</td>
				<td>{{item.price}}</td>
				<td><button v-on:click="remove(index)">Buy</button></td>
			</tr>
		</tbody>
	</table>
</template>
<script>
export default {
	name:"ShoppingList",
	props: ['list'],
	methods:{
		remove:function(index) {
			this.$emit('remove-item',index);
		}
	}
}
</script>

// react/reduxtest/src/components/ShoppingList.js
import React from 'react';
import {connect} from 'react-redux'

class ShoppingList extends React.Component {
	
	removeFromList = (event) => {
		console.log("delete")
		this.props.dispatch({
			type:"REMOVE_FROM_LIST",
			data:event.target.name
		})
	}

	render() {
			let items = this.props.list.map((item) => {
				return <tr key={item.id}>
							<td>{item.count}</td>
							<td>{item.type}</td>
							<td>{item.price}</td>
							<td><button name={item.id} 
							onClick={this.removeFromList}>Remove</button></td>
						</tr>				
			})
	return(
		<table>
			<thead>
				<tr>
					<th>Count</th>
					<th>Type</th>
					<th>Price</th>
					<th>Remove</th>
				</tr>
			</thead>
			<tbody>
				{items}
			</tbody>
		</table>	
		)		
	}
}

const mapStateToProps = (state) => {
	console.log("ShoppingList - mapStateToProps");
	return {
		list: state.list
	}
}

export default connect(mapStateToProps)(ShoppingList);
